version: "3.0"

services:
  pullse:
    build:
      context: .
    environment:
      RUST_LOG: info
      CONFIG_PATH: /usr/local/share/pullse/config/custom
    volumes:
      - ${PULLSE_CONFIG}:/usr/local/share/pullse/config/custom.toml:ro
    ports:
      - "${PULLSE_PORT}:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - pullse
