[common]
pull_timeout = 5000

[gatherers]
    [gatherers.weather]
    enabled = true
    options = { api_key = "123", location = "456" }

[exposers]
    [exposers.prometheus]
    enabled = true
    options = { port = 3000 }
